# Generated by Django 5.0.7 on 2024-10-07 19:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0003_alter_post_image'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='avatar',
            field=models.ImageField(default='static/images/illust58-2722.jpg', null=True, upload_to=''),
        ),
    ]
