# Generated by Django 5.0.7 on 2024-10-29 16:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0009_alter_trip_accommodation_price_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='trip',
            name='car_price_per_person',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=10),
        ),
        migrations.AlterField(
            model_name='trip',
            name='flight_price',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=10),
        ),
        migrations.AlterField(
            model_name='trip',
            name='num_days',
            field=models.PositiveIntegerField(default=0),
        ),
        migrations.AlterField(
            model_name='trip',
            name='total_price',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=15),
        ),
    ]
