# Generated by Django 5.0.7 on 2024-10-29 17:07

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0012_alter_attraction_name_alter_trip_attractions'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='trip',
            name='attractions',
        ),
        migrations.DeleteModel(
            name='Attraction',
        ),
    ]
