# Generated by Django 5.0.7 on 2024-10-29 17:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0013_remove_trip_attractions_delete_attraction'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='trip',
            name='car_distance',
        ),
        migrations.RemoveField(
            model_name='trip',
            name='transport_name',
        ),
        migrations.AddField(
            model_name='trip',
            name='flight_arrival_airport',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='trip',
            name='flight_departure_airport',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
    ]
