# Generated by Django 5.0.7 on 2024-10-29 18:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0014_remove_trip_car_distance_remove_trip_transport_name_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='trip',
            old_name='flight_arrival',
            new_name='flight_back_from',
        ),
        migrations.RemoveField(
            model_name='trip',
            name='flight_arrival_airport',
        ),
        migrations.RemoveField(
            model_name='trip',
            name='flight_departure',
        ),
        migrations.RemoveField(
            model_name='trip',
            name='flight_departure_airport',
        ),
        migrations.AddField(
            model_name='trip',
            name='flight_back_from_airport',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='trip',
            name='flight_back_to',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='trip',
            name='flight_back_to_airport',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='trip',
            name='flight_from',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='trip',
            name='flight_from_airport',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='trip',
            name='flight_to',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='trip',
            name='flight_to_airport',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
    ]
